name: Push-to-EC2

on: push

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: "ubuntu"
          HOST: "ec2-34-201-172-232.compute-1.amazonaws.com"
          KEY: ${{ secrets.PRIVATE_KEY_EC2_DEMO }}
        with:
          source: 'dist/'
          target: '/home/ubuntu/test/'
